name: Build and test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:  # optional: allows manual trigger

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Build wheel
      run: |
        python -m pip install --upgrade pip wheel pytest
        python -m pip wheel . -w wheels

    - name: Install and test
      run: |
        export TQDM_DISABLE=1
        python -m pip install wheels/optical_qrc-*-py3-none-any.whl
        pytest
