name: Publish generated results

on:
  workflow_dispatch:  # optional: allows manual trigger
 
permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Build wheel
      run: |
        python -m pip install --upgrade pip wheel pytest
        python -m pip wheel . -w wheels

    - name: Install and test
      run: |
        python -m pip install wheels/optical_qrc-*-py3-none-any.whl

    - name: Prepare directories
      run: |
        mkdir -p results/figures/pdf results/figures/png results/data

    - name: Run all simulation scripts
      run: |
        export TQDM_DISABLE=1
        for f in simulations/fig*.py; do
          echo "Running $f"
          python "$f"
        done
    
    - name: Generate README.md for figures
      run: |
        echo "# Generated figures" > README.md
        echo "" >> README.md
        for img in results/figures/png/*; do
          filename=$(basename "$img")
          echo "![${filename}](figures/png/${filename})" >> README.md
        done

    - name: Prepare deploy folder
      run: |
        mkdir -p deploy
        cp -r results/figures results/data README.md deploy/

    - name: Deploy to results branch
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: results
        publish_dir: ./deploy
        keep_files: false
