name: Publish generated results

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:  # optional: allows manual trigger

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Build wheel
      run: |
        python -m pip install --upgrade pip wheel pytest
        python -m pip wheel . -w wheels

    - name: Install and test
      run: |
        python -m pip install wheels/optical_qrc-*-py3-none-any.whl
        pytest

    - name: Prepare directories
      run: |
        mkdir -p figures/pdf figures/png results

    - name: Run all simulation scripts
      run: |
        for f in simulations/fig*.py; do
          echo "Running $f"
          python "$f"
        done
    
    - name: Generate README.md for figures
      run: |
        echo "# Generated figures" > README.md
        echo "" >> README.md
        for img in figures/png/*; do
          filename=$(basename "$img")
          echo "![${filename}](figures/png/${filename})" >> README.md
        done

    - name: Deploy figures, results, and README.md to results branch
      run: |
        mkdir -p deploy
        cp -r figures results README.md deploy/
        cd deploy
        git init
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Updated figures and results following commit"
        git branch -M main
        git remote add origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
        git push -f origin main:results
